services:
  - type: web
    name: MetroRouteXpert
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r py-backend/requirements.txt"
    startCommand: "python py-backend/main.py"
    envVars:
      - key: FLASK_ENV
        value: production
