services:
  - type: web
    name: metroroutexpert-backend
    env: python
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: "python py-backend/main.py"
    envVars:
      - key: FLASK_ENV
        value: production
